### ISSUE TITLE
Team drive

### ISSUE THREAD

**Issue by doubektomas** [r12habh/Torrent-To-Google-Drive-Downloader-v2#1]
Hi,
I have been wondering, is there a way to download directly to team drive?

**Comment by NullBruce** [comment]
@doubektomas  yes there's! just copy the path and paste it.

**Comment by gudgobar** [comment]
@NullBruce No it does not work

**Comment by NullBruce** [comment]
@gudgobar it does work for me! if you had a problem screenshot it.

**Comment by oujbih** [comment]
```
params = {
    'save_path': '/content/drive/Shared drives/your_folder_name',
    'storage_mode': lt.storage_mode_t(2),
    'paused': False,
    'auto_managed': True,
    'duplicate_is_error': True}

```

**Comment by gudgobar** [comment]
sorry my bad I changed it to team drive instead of shared drive. Works perfectly.
