### ISSUE TITLE
ModuleNotFoundError: No module named 'libtorrent'

### ISSUE THREAD

**Issue by Ikaedis** [r12habh/Torrent-To-Google-Drive-Downloader-v2#18]
It seems that when installing the Libtorrent dependency, it no longer works

**Comment by choirulzxc** [comment]
wkwkwk. its the same problem.

**Comment by raspi-ux** [comment]
I have the same error

**Comment by alsayer333** [comment]
I have that as well. Someone must fix this. It started happening from today. more or less. " import libtorrent as lt " seems to be not working

**Comment by semarngaji** [comment]
1, Run the first command (Mount Google Drive)
![1](https://user-images.githubusercontent.com/8349031/109079112-0a9b8800-7731-11eb-9260-64cd3452cdec.png)

2. Add code and run these commands separately:
!python -m pip install --upgrade pip setuptools wheel
![2](https://user-images.githubusercontent.com/8349031/109079135-138c5980-7731-11eb-865b-b143d84e8a10.png)

!python -m pip install lbry-libtorrent
![3](https://user-images.githubusercontent.com/8349031/109079159-1be49480-7731-11eb-90f0-c9f48cd2ae0a.png)

3. Install Dependency
![4](https://user-images.githubusercontent.com/8349031/109079181-230ba280-7731-11eb-82f9-866f5403ac44.png)

4. Before running the download command (Code to download torrent), remove these lines:
'paused': False,
'auto_managed': True,
'duplicate_is_error': True
![5](https://user-images.githubusercontent.com/8349031/109079208-30c12800-7731-11eb-89bf-6e8e4d10b865.png)

5. Run it. It works for me!
![6](https://user-images.githubusercontent.com/8349031/109079473-901f3800-7731-11eb-9991-53100a42a5f0.png)
