### ISSUE TITLE
ModuleNotFoundError: No module named 'libtorrent'

### ISSUE THREAD

**Issue by luisjeremias** [r12habh/Torrent-To-Google-Drive-Downloader-v2#19]

**Comment by iWajdi** [comment]
Got the answer from this video:
https://youtu.be/kFG2YHVGZLs

you just add :
!python -m pip install --upgrade pip setuptools wheel
!python -m pip install lbry-libtorrent

however you will be faced with another problem which is:
handle = lt.add_magnet_uri(ses, link, params)
![image](https://user-images.githubusercontent.com/77938896/109280328-2d09d000-781b-11eb-86fc-0fe7520b543b.png)

**Comment by elemefaaoo** [comment]
use version 3

**Comment by elemefaaoo** [comment]
> _No description provided._



> _No description provided._

use version 3

**Comment by nHiRanZ** [comment]
> > _No description provided._
> 
> > _No description provided._
> 
> use version 3

Link to v3?

**Comment by elemefaaoo** [comment]
> > > _No description provided._
> > 
> > 
> > > _No description provided._
> > 
> > 
> > use version 3
> 
> Link to v3?

https://colab.research.google.com/github/ethanaobrien/Torrent-To-Google-Drive-Downloader-v2/blob/master/Torrent_To_Google_Drive_Downloader_v3.ipynb

**Comment by elemefaaoo** [comment]
> > > _No description provided._
> > 
> > 
> > > _No description provided._
> > 
> > 
> > use version 3
> 
> Link to v3?

https://github.com/r12habh/Torrent-To-Google-Drive-Downloader-v2/pulls
