### ISSUE TITLE
How

### ISSUE THREAD

**Issue by isamuakira** [r12habh/Torrent-To-Google-Drive-Downloader-v2#2]
How to delete after disk full?

**Comment by rltim151** [comment]
Which delete are you talking about? If it is about the collab's drive then you just terminate the drive and reconnect it 👍

**Comment by S4MUR411** [comment]
can i download a torrent half then resume the torrent later in different session?

**Comment by r12habh** [comment]
> can i download a torrent half then resume the torrent later in different session?

No you can't because its not a torrent client.
