### ISSUE TITLE
[Request] Add option to download multiple magnet

### ISSUE THREAD

**Issue by sobuj53** [r12habh/Torrent-To-Google-Drive-Downloader-v2#6]
Hello,

This is great way to download torrent using google's computing power. However can you please make a way to download multiple magnet link at a time. As we're using google's server power, I think it will be a great way to use its resource to the full capacity.

Thank you for your time and consideration.

**Comment by r12habh** [comment]
you can make a copy of the cell where you put the download link and run it
So the next torrent will be downloaded in the serial order after the previous one is finished.
