### ISSUE TITLE
[REQ] + HELP

### ISSUE THREAD

**Issue by KingWiscol** [r12habh/Torrent-To-Google-Drive-Downloader-v2#8]
so there is a part where "PASTE TORRENT/MAGNET LINK HERE ",the question is how to paste the torrent file, then is it possible if we choose a specific file inside a torrent

**Comment by r12habh** [comment]
No its not possible to select a specific file inside the torrent, the whole package will be downloaded.

**Comment by KingWiscol** [comment]
ohh ok ok, thanks

**Comment by KingWiscol** [comment]
ohh ok ok, thanks
