### ISSUE TITLE
WebTorrent

### ISSUE THREAD

**Issue by zero77** [r12habh/Torrent-To-Google-Drive-Downloader-v2#9]
is it possible to use web torrent to stream torrents instead of downloading them.

**Comment by sobuj53** [comment]
you can download it to google team drive (with lots of space on it) and then stream from it.

**Comment by zero77** [comment]
@r12habh @sobuj53 
What about a scenario where you don't want to download anything.
But, want to make use of the increased speed and stream something instead.

**Comment by sobuj53** [comment]
Don’t know. but speaking of downloading, technically you are not downloading it to your local storage but in cloud. And if you use team drive it’s not even costing you any space, also if the torrent has good seed it will be transfered in moment, so...
